/**
 * HTML template generator for coverage report.
 * 
 * Generates a complete, self-contained HTML document with inline CSS and JavaScript.
 */

import type { CoverageReport } from "../../types/index.js";
import { safeJsonSerialize } from "./utils.js";
import { CSS_STYLES } from "./styles.js";
import { JS_SCRIPTS } from "./scripts.js";
import {
  renderSummary,
  renderPackagesTable,
  renderComponentsTable,
  renderNativeElementsTable,
  renderCustomComponentsTable,
  renderReplacementCandidatesTable,
  renderMetadata,
} from "./components.js";

/**
 * Generates the complete HTML document for the coverage report.
 * 
 * @param report - The coverage report data
 * @returns Complete HTML document as string
 */
export function generateHtml(report: CoverageReport): string {
  const timestamp = new Date().toISOString();
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="generator" content="@waysnx/ui-kit-coverage v${report.analyzerVersion}">
  <title>UI Kit Coverage Report - ${report.project.name}</title>
  <style>${CSS_STYLES}</style>
</head>
<body>
  <div id="top"></div>
  <div class="container">
    ${renderHeader(report, timestamp)}
    ${renderControls()}
    ${renderSummary(report)}
    ${renderPackagesTable(report)}
    ${renderComponentsTable(report)}
    ${renderNativeElementsTable(report)}
    ${renderCustomComponentsTable(report)}
    ${renderReplacementCandidatesTable(report)}
    ${renderMetadata(report)}
    ${renderFooter(report)}
  </div>
  
  <script>
    // Embedded coverage data (for future export/processing features)
    window.__COVERAGE_REPORT__ = ${safeJsonSerialize(report)};
  </script>
  <script>${JS_SCRIPTS}</script>
</body>
</html>`;
}

/**
 * Renders the report header.
 */
function renderHeader(report: CoverageReport, timestamp: string): string {
  return `
    <header class="report-header">
      <h1 class="report-title">UI Kit Coverage Report</h1>
      <p class="report-subtitle">${report.project.name}</p>
      <div class="report-meta">
        <span>Analyzer v${report.analyzerVersion}</span>
        <span>•</span>
        <span>Schema v${report.schemaVersion}</span>
        <span>•</span>
        <span>Generated ${new Date(timestamp).toLocaleString()}</span>
      </div>
    </header>
  `;
}

/**
 * Renders the control bar with search and theme toggle.
 */
function renderControls(): string {
  return `
    <div class="controls">
      <input 
        type="search" 
        id="search-box" 
        class="search-box" 
        placeholder="Search across all tables... (Ctrl+K)"
        aria-label="Search coverage report"
      />
      <button 
        type="button" 
        id="theme-toggle" 
        class="theme-toggle"
        aria-label="Toggle dark mode"
      >
        🌙 Dark Mode
      </button>
    </div>
  `;
}

/**
 * Renders the report footer.
 */
function renderFooter(report: CoverageReport): string {
  return `
    <footer style="text-align: center; padding: var(--spacing-xl) 0; border-top: 1px solid var(--border-color); margin-top: var(--spacing-xl); color: var(--text-muted); font-size: 0.875rem;">
      <p>
        Generated by <strong>@waysnx/ui-kit-coverage</strong> v${report.analyzerVersion}
      </p>
      <p style="margin-top: var(--spacing-xs);">
        <a href="#top" style="color: var(--accent-primary); text-decoration: none;">↑ Back to Top</a>
      </p>
      <p style="margin-top: var(--spacing-md); font-size: 0.75rem;">
        Keyboard shortcuts: <kbd>Ctrl+K</kbd> Search • <kbd>Ctrl+D</kbd> Toggle Theme
      </p>
    </footer>
  `;
}
